name: Caching and artifacts
on: [workflow_dispatch]

jobs:
  caching-and-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install dependencies
        run: npm install
      - name: cache node modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-cache-${{hashFiles('**/package-lock.json')}}
          restore-keys: |
            npm-cache
      - name: display cache output
        run: echo "caching output result- ${{ toJson(steps.cache-node-modules.outputs) }}"
      - name: use axios
        uses: actions/github-script@v6
        with:
          script: |
            const axios = require('axios')
            const result = await axios.get('https://icanhazdadjoke.com/', {
              headers: {
                'Accept': 'text/plain'
              }
            })
            console.log(result.data)

      # The following part is from artifact lesson
      - name: run test
        run: npm test
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage
          path: coverage
          retention-days: 1
      - name: download artifact
        uses: actions/download-artifact@v3
        with:
          name: code-coverage
          path: code-coverage-report
      - run: ls -a
      - run: ls -a
        working-directory: code-coverage-report
