name: Caching and artifacts
on: [workflow_dispatch]

jobs:
  caching-and-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install dependencies
        run: npm install
      - name: use axios
        uses: actions/github-script@v6
        with:
          script: |
            const axios = require('axios')
            const result = await axios.get('https://icanhazdadjoke.com/', {
              headers: {
                'Accept': 'text/plain'
              }
            })
            console.log(result)
            