name: Call reusable workflow
on:
  workflow_dispatch: 
    inputs:
      name:
        type: string
        required: false
        default: "Abdullah Al Noman"
        description: Enter name
      
jobs:
  call-reusable-wf-same-repository:
    uses: ./.github/workflows/reusable-wf.yaml
    secrets: inherit
  log-output-from-reusable-wf:
    runs-on: ubuntu-latest
    needs: call-reusable-wf-same-repository
    steps:
      - name: log output
        run: echo "${{ needs.call-reusable-wf-same-repository.outputs.date }}"
