name: Concurrency-1
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Environment
        required: true
concurrency: 
  group: ${{ inputs.environment }}
  cancel-in-progress: true

jobs:
  just-sleep:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30