name: Concurrency-1
run-name: running ยง${{github.workflow}} workflow for ยง${{inputs.environment}} environment
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Environment
        required: true
concurrency: 
  group: ${{ github.workflow }}-${{ inputs.environment }}
  cancel-in-progress: true

jobs:
  just-sleep:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30
