name: Dynamic Matrix
on:
  workflow_dispatch:
    inputs:
      os:
        type: string
        default: "ubuntu-latest,macos-latest"
        description: Runner OS
      node-version:
        type: string
        default: "14,16"
        description: Node version

jobs:
  prepare-input:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.scripter.outputs.result }}
    steps:
      - uses: actions/github-script@v6
        id: scripter
        with:
          result-encoding: json
          script: "return {'os': context.payload.inputs['os'].split(','), 'node-version': context.payload.inputs['node-version'].split(',')}"
      - run: echo "output from scripter= ${{ steps.scripter.outputs.result }}"
      - run: echo "step-output=value" >> $GITHUB_OUTPUT
        id: step-1
      - run: echo "step-output=value from step 2" >> $GITHUB_OUTPUT
        id: step-2
      - name: log the generated output from step-1 and step-2
        run: |
          echo "${{ steps.step-1.outputs.step-output }}"
          echo "${{ steps.step-2.outputs.step-output }}"
  
  dynamic-matrix:
    needs: prepare-input
    strategy:
      matrix:
        os: ${{ fromJson(needs.prepare-input.outputs.result).os }}
        node-version: ${{ fromJson(needs.prepare-input.outputs.result).node-version }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: node -v
      - name: display matrix
        run: echo "${{ toJson(matrix) }}"
        