name: Dynamic Matrix
on:
  workflow_dispatch:
    inputs:
      os:
        type: string
        default: "ubuntu-latest,macos-latest"
        description: Runner OS
      node-version:
        type: string
        default: "14,16"
        description: Node version

jobs:
  prepare-input:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: scripter
        with:
          result-encoding: json
          script: "return {'os': context.payload.inputs['os'].split(','), 'node-version': context.payload.inputs['node-version'].split(',')}"
      - run: echo "output from scripter= ${{ steps.scripter.outputs.result }}"
      - run: echo "step-output=value" >> $GITHUB_OUTPUT
        id: step-1
      - run: echo "step-output=value from step 2" >> $GITHUB_OUTPUT
        id: step-2
      - name: log the generated output from step-1 and step-2
        run: |
          echo "${{ steps.step-1.outputs.step-output }}"
          echo "${{ steps.step-2.outputs.step-output }}"
