name: Environment vars different level
on:
  - push
env:
  WF_LEVEL: This env is from workflow level

jobs:
  job-1:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env: 
      JOB_LEVEL: This env is from job level
    steps:
      - name: log github ref
        run: |
          echo "github ref from env var: $GITHUB_REF"
          echo "github ref from context: ${{ github.ref }}"
          echo $GITHUB_ENV
          echo EOF
      - name: set dynamic env var
        run: |
          echo "ENV_DATE=$(date)" >> "$GITHUB_ENV"
          echo "ENV_RANDOM=$RANDOM" >> "$GITHUB_ENV"
      - name: set multiline dynamic env var
        run: |
          DELIMITER=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          {
            echo "ENV_RAND_JOKE<<$DELIMITER"
            curl -s https://icanhazdadjoke.com/
            echo $DELIMITER
          } >> "$GITHUB_ENV"

      - name: log all level custom env
        env:
          STEP_LEVEL: This env is from step level
        run: |
          echo $WF_LEVEL
          echo $JOB_LEVEL
          echo $STEP_LEVEL
          echo $ENV_DATE
          echo $ENV_RANDOM
          echo $ENV_RAND_JOKE
      - name: log wf and job level custom env
        run: |
          echo $WF_LEVEL
          echo $JOB_LEVEL
          echo 'Not shown: $STEP_LEVEL'
  job-2:
    runs-on: ubuntu-latest
    steps:
      - name: only wf level env
        run: |
          echo $WF_LEVEL
          echo 'Not shown: $JOB_LEVEL'
          echo 'Not shown: $STEP_LEVEL'
