name: Running a job multiple time using Matrix
on: [push]

jobs:
  node-matrix:
    runs-on: ubuntu-latest
    steps:
      - run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: node -v
          