name: Running a job multiple time using Matrix
on: [push]

jobs:
  node-matrix:
    strategy:
      matrix:
        os-selector: [ubuntu-latest, windows-latest]
        node-version-selector: [14, 15, 16]
    runs-on: ${{ matrix.os-selector }}
    steps:
      - run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version-selector }}
      - run: node -v
          