name: Running a job multiple time using Matrix
on: [push]

jobs:
  node-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version-selector: [14, 15, 16]
    steps:
      - run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version-selector }}
      - run: node -v
          