name: Reusable workflow in same repository
on:
  workflow_call:
    outputs:
      date:
        description: Current date-time
        value: ${{ jobs.generate-output.outputs.date }}

jobs:
  call-reusable-wf:
    uses: inception-maker/reusable-wf-container/.github/workflows/reusable-workflow.yaml@main
    with:
      name: ${{ inputs.name }}
    secrets: 
      access_token: ${{ secrets.PASSPHRASE }}
  generate-output:
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.generate-output.outputs.date }}
    steps:
      - name: generate output
        id: generate-output
        run: echo "date=$(date)" >> $GITHUB_OUTPUT
