name: Scheduled wf to mark stale issues & PRs
on:
  schedule:
    - cron: '0/1 * * * *'

jobs:
  mark-pr-stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          stale-pr-message: "Marking this PR as stale, since it is hanging there for a long time"
          stale-pr-label: "bug"
          days-before-pr-stale: 0
          days-before-pr-close: 5
          
    permissions:
      pull-requests: write
      