name: variables and secrets
on: [push]

jobs:
  var-and-secret-different-level:
    runs-on: ${{ vars.RUNNER_OS }}
    environment: prod
    env:
      ORG_ENV_VAR: ${{ vars.ORG_ENV_VAR }}
      REPOSITORY_ENV_VAR: ${{ vars.REPOSITORY_ENV_VAR }}
      ENV_ENV_VAR: ${{ vars.ENV_ENV_VAR }}
      ORG_SECRET_BOOLEAN: ${{ secrets.ORG_SECRET_BOOLEAN }}
      REPOSITORY_BOOLEAN_SECRET: ${{ secrets.REPOSITORY_BOOLEAN_SECRET }}
      ENV_LEVEL_BOLEAN: ${{ secrets.ENV_LEVEL_BOLEAN }}
    steps:
      - name: run only on production environment
        if: env.ENV_LEVEL_BOLEAN == 'true'
        run: echo "I ran because of production environment"
      - name: log all env vars and secrets
        run: |
          echo $ORG_ENV_VAR
          echo $REPOSITORY_ENV_VAR
          echo $ENV_ENV_VAR
          echo $ORG_SECRET_BOOLEAN
          echo $REPOSITORY_BOOLEAN_SECRET
          echo $ENV_LEVEL_BOLEAN
