name: WF triggered by other WF
on:
  workflow_run:
    workflows: [Run WF when all filters are passed]
    types: completed
    branches:
      - main

jobs:
  just-echo-hello-world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World, triggered by other workflow"
